### ISSUE TITLE
Improperly parses git SSH url with a port 

### ISSUE THREAD

**Issue by nogweii** [ruifm/gitlinker.nvim#12]
`url_data` in the callback looks like:

```
{
  file = "config/nvim/init.lua",
  host = "code.aether.earth",
  repo = "22792/nogweii/dotfiles",
  rev = "cca9fc53bff70206d9878549184b6cff5606dce5"
}
```

While my git remote URL is: `ssh://git@code.aether.earth:22792/nogweii/dotfiles.git`

I expected `host` to include the port, rather than the `repo`, since it's all numbers.

Though, then there is the secondary want of it *not* including the port at all, since gitlab is accessible on HTTP's regular port. :laughing:

---------

This might be an odd enough case, so perhaps this just needs to be handled by a custom callback?

**Comment by ruifm** [comment]
Thanks for the report.

It's not an odd case at all, I think the solution is to parse the port if it exists and add it to the `url_data` table.

Then a user can optionally use it in the callbacks.

I will soon address this.

**Comment by ruifm** [comment]
https://github.com/ruifm/gitlinker.nvim/pull/13
