### ISSUE TITLE
Issue with error message with no matching callback

### ISSUE THREAD

**Issue by AckslD** [ruifm/gitlinker.nvim#16]
**Describe the bug**
Before I had properly configured my company's gitlab ie:
```
callbacks = {
  ["git.seriouscompany.com"] = require"gitlinker.hosts".get_gitlab_type_url
}
```
when gitlinker hit [this line](https://github.com/ruifm/gitlinker.nvim/blob/a89d865d98500a908ef05b0d5934eaf771d0e398/lua/gitlinker/hosts.lua#L116) to print the error message it failed and said that `target_host` wasn't a string but a number. 
```
E5108: Error executing lua ...pack/packer/start/gitlinker.nvim/lua/gitlinker/hosts.lua:116: bad argument #2 to 'error' (number expected, got string)
```

**To Reproduce**
See above.

**Expected behavior**
Getting the error `"No host callback defined for host 'git.seriouscompany.com'"`

**System (please complete the following information):**
 - OS: archlinux
 - `neovim --version` v0.5.0-dev+1419-gf76f72a27
- `git --version` 2.32.0

**Comment by ruifm** [comment]
Thanks for the report! I think I fixed with https://github.com/ruifm/gitlinker.nvim/pull/17, feel free to reopen, if it's still not fixed for you.
