### ISSUE TITLE
open repo homepage

### ISSUE THREAD

**Issue by rafamadriz** [ruifm/gitlinker.nvim#22]
This was talked about in #19, this issue is just for tracking.

**Comment by ruifm** [comment]
@rafamadriz  let me know if https://github.com/ruifm/gitlinker.nvim/pull/23 works for you.

You can check the README's diff for the instruction on the mapping for repo homepage url generation.

**Comment by rafamadriz** [comment]
> @rafamadriz let me know if #23 works for you.
> 
> You can check the README's diff for the instruction on the mapping for repo homepage url generation.

@ruifm awesome, that is working for me.
