### ISSUE TITLE
Sourcehut links broken - missing user/namespace

### ISSUE THREAD

**Issue by samhh** [ruifm/gitlinker.nvim#36]
Generated Sourcehut links are broken. GitHub is fine. Unmodified `callbacks` config. Happens with all my repos, example: https://git.sr.ht/~samhh/bangin

The output is: `https://git.sr.ht/bangin/tree/a99b870dfe56d6b79988d98bf71d5a0b7f6cd4e1/item/bangin.sh#L6`

But should be: `https://git.sr.ht/~samhh/bangin/tree/a99b870dfe56d6b79988d98bf71d5a0b7f6cd4e1/item/bangin.sh#L6`

Note the additional `/~samhh`. I'm not sure how the repo remote is calculated but it should be parseable:

```
$ git remote -v
origin	git@git.sr.ht:~samhh/bangin (fetch)
origin	git@git.sr.ht:~samhh/bangin (push)
```

**Comment by ruifm** [comment]
Thanks for the detailed issue report.

I found the cause:

https://github.com/ruifm/gitlinker.nvim/blob/003ee482a25118cdac73faea8bd35df0399e8f8f/lua/gitlinker/git.lua#L147-L150

it's missing `~` as an allowed char. I will file a PR soon, if I forget, feel free to ping me.

**Comment by samhh** [comment]
Just wanted to confirm it's fixed on my end, many thanks!
