### ISSUE TITLE
Documentation: Make it clearer that callback entries are match patterns

### ISSUE THREAD

**Issue by Rahix** [ruifm/gitlinker.nvim#41]
Hi,

I recently had an unpleasant experience where gitlinker just would not work for a certain gitlab host.  I pulled my hair out over it until I noticed the culprit:  the hostname contained a `-` symbol, like `gitlab.foo-bar.com`.  Duly following the example in the README, I added

```lua
  callbacks = {
        -- ...
        ["gitlab.foo-bar.com"] = require("gitlinker.hosts").get_gitlab_type_url,
  },
```

to my config.  But after reading through the relevant code, I saw that `string.match()` is used with these entries:

https://github.com/ruifm/gitlinker.nvim/blob/a11e5fa14bbb438f59a3744bff53a3ad78eecd71/lua/gitlinker/hosts.lua#L174

Of course this makes sense to do because it allows regex (if you can call it that) matching of many hosts with a single entry.  But as lua regex treats `-` specially, my string would never match the host.

I want to make sure that others won't run into this problem as well.  However I am unsure what can be done about it.  I see two options:

1. It feels slightly dirty, but trying an exact match before doing the regex match would probably work just fine.  Regex patterns will most likely never plainly match a hostname so I think it would be okay to do this.  So something like
   ```lua
   if target_host == host or target_host:match(host) then
   ```
2. Documenting this fact much more prominently could also work.  I am not sure how much this will guard people from running into the same trap but, for example, changing the example in the README to properly match its intended hostnames would go a long way:
   ```diff
    callbacks = {
   -  ["github.com"] = require"gitlinker.hosts".get_github_type_url,
   -  ["gitlab.com"] = require"gitlinker.hosts".get_gitlab_type_url,
   -  ["try.gitea.io"] = require"gitlinker.hosts"get_gitea_type_url,
   +  ["github%.com"] = require"gitlinker.hosts".get_github_type_url,
   +  ["gitlab%.com"] = require"gitlinker.hosts".get_gitlab_type_url,
   +  ["try%.gitea%.io"] = require"gitlinker.hosts"get_gitea_type_url,
    },
   ```

What do you think?

That all said, I love this plugin, it helps my workflow a lot :)

**Comment by ruifm** [comment]
I actually had this issue a while ago but completely forgot about it, thanks for bring it up!



> 1. It feels slightly dirty, but trying an exact match before doing the regex match would probably work just fine.  Regex patterns will most likely never plainly match a hostname so I think it would be okay to do this.  So something like
>        ```lua
>        if target_host == host or target_host:match(host) then
>        ```

I prefer option 1 + leaving a note in the docs that "lua regexes" are allowed instead. I'm a bit busy this weekend so if you want to file a PR with that, I would appreciate it, if not I can do it later.

I even admit to remove the regex matching feature since I doubt no-one is using it anyway, maybe it's not worth the trouble/bugs.

>That all said, I love this plugin, it helps my workflow a lot :)

Thanks for the kind words!
