### ISSUE TITLE
Open in browser doesn't work anymore with latest gitlinker and nvim version

### ISSUE THREAD

**Issue by huyvohcmc** [ruifm/gitlinker.nvim#56]
**Config**
```
local linker = require 'gitlinker'
local actions = linker.actions
local set = vim.keymap.set

linker.setup {
  mappings = nil,
}

set('n', 'gl', function()
  linker.get_buf_range_url('n', {action_callback = actions.open_in_browser})
end)

set('v', 'gl', function()
  linker.get_buf_range_url('v', {action_callback = actions.open_in_browser})
end)

set('n', 'gB', function()
  linker.get_repo_url({action_callback = actions.open_in_browser})
end)
```

**Expected**
Open the generated URL in the browser.

**Actual**
The generated URL is printed in `:messages`.

**System:**
 - OS: macos 12.3.1
 - `neovim --version`
```
NVIM v0.8.0-dev
Build type: Release
LuaJIT 2.1.0-beta3
```

I tried downgrading nvim to version 0.7.0 and the bug still happens.

**Comment by huyvohcmc** [comment]
My `packer_compiled.lua` file has some issues, after uninstalled and reinstalled all plugins, `open_in_browser` now works normally.

**Comment by tsakirist** [comment]
@ruifm any updates on this?  just checked it again and it still doesn't work

**Comment by Danielwsx64** [comment]
@ruifm I have the same issue. I noticed that `plenary.job` for some reason I don´t understand can´t run `xdg-open` correctly. If I add a custom callback running `io.popen("xdg-open " .. url)` It works fine.

I tried calling the browser with `plenary.job` and it works fine too:

```lua
Job:new({ command = "firefox", args = { url } }):sync()

**Comment by joe-rocko** [comment]
mine shows the url at the bottom but doesn't proceed to open the browser
