### ISSUE TITLE
Calling `get_buf_range_url` through a user command not including ranges

### ISSUE THREAD

**Issue by smarquez1** [ruifm/gitlinker.nvim#62]
Hi, I created a user command [based on a user's comment](https://github.com/ruifm/gitlinker.nvim/issues/29#issuecomment-905704175) to open the current selected lines on github.
The problem is that, in Visual mode, it will not add the current code range to the URL.
Am I missing to pass something  to the new user command or maybe this is a bug?

```lua
local linker = require "gitlinker"
local actions = require "gitlinker.actions"

function _G.gitOpenInBrowser(t)
  local mode = t.range > 0 and "v" or "n"
  linker.get_buf_range_url(mode, { action_callback = actions.open_in_browser })
end

vim.api.nvim_create_user_command(
  "GitOpenInBrowser",
  gitOpenInBrowser,
  { desc = "Open file in github", range = true }
)
```

**Comment by GlebBeloded** [comment]
I am terrible at neovim and lua, but for me changing 
[these two lines](https://github.com/ruifm/gitlinker.nvim/blob/cc59f732f3d043b626c8702cb725c82e54d35c25/lua/gitlinker/buffer.lua#L18-#L19) to
```lua
    local pos1 = vim.api.nvim_buf_get_mark(0, "<")[1]
    local pos2 = vim.api.nvim_buf_get_mark(0, ">")[1]
```
seemed to solve the issue

**Comment by smarquez1** [comment]
Hey @GlebBeloded what problem where you getting exactly?
I think that the original issue got somewhat solved, but it's still buggy.

Right now I use lazy.nvim to setup my plugins including keymaps. This is how I setup gitlinker:

```lua
function _G.gitOpenInBrowser(mode)
  local linker = require "gitlinker"
  local actions = require "gitlinker.actions"
  local callback = { action_callback = actions.open_in_browser }
  linker.get_buf_range_url(mode, callback)
end

return {
  "ruifm/gitlinker.nvim",
  config = function() require("gitlinker").setup() end,
  keys = {
    ...
    { "<leader>gB", function() _G.gitOpenInBrowser("n") end, },
    { "<leader>gB", function() _G.gitOpenInBrowser("v") end, mode = "v",
    },
  },
}
```

The problem I'm getting now is that while gitlinker opens up a browser with a code region highlighted, the range code is displaced by one line both at the beginning and the end.

Is that the issue that your comment fixes?

**Comment by GlebBeloded** [comment]
@smarquez1 
My issue was that 
```lua
local pos1 = vim.fn.getpos("v")[2]
local pos2 = vim.fn.getcurpos()[2]
```

returned the same number, because I called gitlinked code not from a binding, but from user-defined command.
I've done a little googling and [this](https://vi.stackexchange.com/questions/31420/how-to-get-the-range-of-selected-lines-in-visual-lines-mode) post suggested, that when you start typing a command, you leave visual mode.

So the edit I've shown you above gets last visual selection, even if you are in normal mode now. 

My command looks like this: 
```lua
vim.api.nvim_create_user_command("Gitlink", function(t)
	local mode = t.range > 0 and "v" or "n"

	require("gitlinker").get_buf_range_url(mode, { action_callback = require("gitlinker.actions").copy_to_clipboard })
end, { range = true })
```

The code range is not displaced also on my end, so maybe it will fix stuff for you too.
